config/routes.rb
Rails.application.routes.draw do
  root to: 'articles#index'

  resources :articles do
    resources :comments
  end

  get 'users/signup', to: 'users#new'
  resources :users, except: :new

  get 'login', to: 'sessions#new'
  post 'login', to: 'sessions#create'
  delete 'logout', to: 'sessions#destroy'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/article.rb
class Article < ApplicationRecord
  MINIMUM_TITLE_LENGTH = 5

  has_many :comments, dependent: :destroy
  belongs_to :user

  validates :title, presence: true, length: { minimum: 5 }
  validates :title, presence: true, length: { minimum: MINIMUM_TITLE_LENGTH }
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :article

  belongs_to :user

  validates :body, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  MAXIMUM_NAME_LENGTH = 255
  MAXIMUM_EMAIL_LENGTH = 50
  MINIMUM_PASSWORD_LENGTH = 6
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-]+(\.[a-z\d\-]+)*\.[a-z]+\z/i

  has_secure_password

  has_many :articles, dependent: :destroy
  has_many :comments, dependent: :destroy

  before_save :email_to_downcase

  validates :name, presence: true, length: { maximum: MAXIMUM_NAME_LENGTH }
  validates :email, presence: true, length: { maximum: MAXIMUM_EMAIL_LENGTH },
                    format: { with: VALID_EMAIL_REGEX },
                    uniqueness: true
  validates :password, presence: true, length: { minimum: MINIMUM_PASSWORD_LENGTH }

  private

  def email_to_downcase
    self.email = email.downcase
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  include SessionsHelper
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  def index
    @articles = Article.all

    render :index
  end

  def show
    @article = Article.find(params[:id])
    @comments = @article.comments.order(created_id: :desc)
  end

  def new
    session_notice(:danger, 'You must be logged in!') unless logged_in?

    @article = Article.new
  end

  def create
    @article = Article.new(article_params)
    @article.user = current_user

    if @article.save
      redirect_to @article
    else
      render :new
    end
  end

  def edit

    if logged_in?
      session_notice(:danger, 'Wrong User') unless equal_with_current_user?(@article.user)
    end

    @article = Article.find(params[:id])
    session_notice(:danger, 'Wrong User') unless equal_with_current_user?(@article.user)
  end

  def update
    @article = Article.find(params[:id])

    if @article.update(article_params)
      redirect_to @article
    else
      render :edit
    end
  end

  def destroy
    session_notice(:danger, 'You must be logged in!') unless logged_in?

    article = Article.find(params[:id])


    if equal_with_current_user?(article.user)
      article.destroy
      redirect_to articles_path
    else
      session_notice(:danger, 'Wrong User')
    end
  end

  private

  def article_params
    params.require(:article).permit(:title, :body)
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  def new
    session_notice(:danger, 'You must be logged in!', login_path) unless logged_in?

    @article = Article.find(params[:article_id])
    @comment = @article.comments.build
  end

  def create
    @article = Article.find(params[:article_id])
    @comment = @article.comments.build(comment_params)
    @comment.user = current_user

    if @comment.save
      redirect_to @article
    else
      render :new
    end
  end

  def destroy
    session_notice(:danger, 'You must be logged in!', login_path) unless logged_in?

    comment = Comment.find(params[:id])


    redirect_to comment.article
    if equal_with_current_user?(comment.user)
      comment.destroy
      redirect_to comment.article
    else
      session_notice(:danger, 'Wrong User')
    end
  end

  def edit
    session_notice(:danger, 'You must be logged in!', login_path) unless logged_in?

    @comment = Comment.find(params[:id])

    if logged_in?
      session_notice(:danger, 'Wrong User') unless equal_with_current_user?(@comment.user)
    end

    @article = @comment.article
  end

  def update
    @comment = Comment.find(params[:id])
    @article = @comment.article

    if @comment.update(comment_params)
      redirect_to @article
    else
      render :edit
    end
  end

  private

  def comment_params
    params.require(:comment).permit(:commenter, :body)
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
    session_notice('warning', 'Already logged in!') if logged_in?
  end

  def create
    user = User.find_by(email: params[:session][:email])

    if user&.authenticate(params[:session][:password])
      log_in(user)
      flash[:success] = "Welcome #{user.name} !"
      redirect_to user

    else
      flash.now[:danger] = 'Email and password miss match'
      render :new
    end
  end

  def destroy
    log_out

    redirect_to root_path
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
    session_notice(:warning, 'Already logged in!') if logged_in?

    @user = User.new
  end

  def create
    @user = User.new(user_params)

    if @user.save
      log_in(@user)
      redirect_to @user
    else
      render :new
    end
  end

  def show
    @user = User.find(params[:id])
  end

  private
  def user_params
    params.require(:user).permit(:name,:email,:password,:password_confirmation)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
  def log_in(user)
    session[:user_id] = user.id
  end

  def current_user
    if session[:user_id]
      @current_user ||= User.find_by(id: session[:user_id])
    end
  end

  def logged_in?
    current_user.present?
  end

  def log_out
    session.delete(:user_id)
    @current_user = nil
  end

  def session_notice(type, message, path = root_path)
    flash[type.to_sym] = message
    redirect_to path and return
  end

  def equal_with_current_user?(other_user)
    current_user == other_user
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/articles/_article.html.erb
<div class="column is-6 is-offset-3">
  <div class="card">
    <% unless local_assigns[:show] %>
      <header class="card-header">
          <p class="card-header-title">
            <%= article.title %>
          </p>
      </header>
    <% end %>
    <div class="card-content">
      <div class="content">
        <p><%= article.body %></p>
      </div>
    </div>
    <footer class="card-footer">
      <% if local_assigns[:show] %>
        <%= link_to "Back", root_path, class: "card-footer-item" %>
      <% else %>
        <%= link_to "Show", article_path(article), class: "card-footer-item" %>
      <% end %>
      <% if logged_in? && equal_with_current_user?(article.user) %>
        <%= link_to "Edit", edit_article_path(article), class: "card-footer-item" %>
      <% end %>

       <% if local_assigns[:show] && logged_in? %>
        <%= link_to "New Comment", new_article_comment_path(article), class: "card-footer-item" %>
      <% end %>

     <% if logged_in? && equal_with_current_user?(article.user) %>
        <%= link_to "Delete", article_path(article), method: :delete,
            data: { confirm: "Are you sure you want to delete this article?" },
            class: "card-footer-item" %>
      <% end %>
    </footer>
  </div>
</div>

app/views/articles/_form.html.erb
<div class="container">
  <div class="columns is-multiline">
    <% if article.errors.any? %>
      <div class="column is-6 is-offset-3">
        <article class="message is-danger">
          <div class="message-body">
            <p><%= pluralize(article.errors.count, "error") %> prohibited this article from being saved:</p>
            <br>
            <p>
            <% article.errors.full_messages.each do |msg| %>
              <li><%= msg %></li>
            <% end %>
            </p>
          </div>
        </article>
      </div>
    <% end %>

    <div class="column is-6 is-offset-3">
      <div class="content is-size-3">
        <h1><%= heading %></h1>
      </div>
    </div>

    <div class="column is-6 is-offset-3">
      <%= form_with model: article, local: true do |form| %>
        <div class="field">
          <%= form.label :title, class: "label" %>
          <div class="control">
            <%= form.text_field :title, class: "input", placeholder: "Title" %>
          </div>
          <% if article.errors.any? %>
            <p class="help is-danger">This title is invalid</p>
          <% end %>
        </div>

        <div class="field">
          <%= form.label :body, class: "label" %>

          <div class="control">
            <%= form.text_area :body, class: "textarea", placeholder: 'Your body' %>
          </div>
        </div>

        <div class="field is-grouped">
          <div class="control">
            <%= form.submit submit, class: "button is-link" %>
          </div>
          <div class="control">
            <%= link_to "Cancel", cancel_path, class: 'button is-link is-light' %>
          </div>
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/articles/edit.html.erb
<%= render 'form',
  article: @article,
  submit: 'Update Article',
  cancel_path: article_path(@article),
  heading: 'Edit Article' %>

app/views/articles/index.html.erb
<div class="container">
  <div class="columns is-multiline">
    <div class="column is-6 is-offset-3">
      <div class="content is-size-3">
        <h1>Articles</h1>
      </div>
    </div>

  <%= render @articles %>
  </div>
</div>

app/views/articles/new.html.erb
<%= render 'form',
  article: @article,
  submit: 'Save Article',
  cancel_path: root_path,
  heading: 'New Article' %>

app/views/articles/show.html.erb
<div class="container">
  <div class="columns is-multiline">
    <div class="column is-6 is-offset-3">
      <div class="content is-size-3">
        <h1><%= @article.title %></h1>
      </div>
    </div>

    <%= render @article, show: true %>

    <%= render @comments %>
  </div>
</div>

app/views/comments/_comment.html.erb
<div class="column is-6 is-offset-3 comment">
  <article class="media">
    <div class="media-content">
      <div class="content">
        <p>
           <strong><%= comment.commenter %></strong> <small><%= time_ago_in_words(comment.created_at) %> ago </small>
          <br>
          <%= comment.body %>
        </p>
      </div>
      <nav class="level is-mobile">
        <% if equal_with_current_user?(comment.user) %>
          <div class="level-left">
            <%= link_to edit_article_comment_path(comment.article, comment), class: "level-item" do %>
              <span class="icon is-small"><i class="fas fa-edit"></i></span>
            <% end %>
            <%= link_to article_comment_path(comment.article, comment), method: :delete , class: "level-item", data: { confirm: "Are you sure you want to delete this comment?" } do %>
              <span class="icon is-small"><i class="fas fa-trash-alt"></i></span>
            <% end %>
          </div>
        <% end %>
      </nav>
    </div>
  </article>
</div>

app/views/comments/_form.html.erb
<div class="container">
  <div class="columns is-multiline">
    <div class="column is-6 is-offset-3">
      <div class="content is-size-3">
        <h1 class="title"><%= heading %>  </h1>
      </div>
    </div>

    <% if comment.errors.any? %>
      <div class="column is-6 is-offset-3">
        <article class="message is-danger">
          <div class="message-body">
            <p><%= pluralize(comment.errors.count, "error") %> prohibited this comment from being saved:</p>
            <br>
            <p>
            <% comment.errors.full_messages.each do |msg| %>
              <li><%= msg %></li>
            <% end %>
            </p>
          </div>
        </article>
      </div>
    <% end %>

    <div class="column is-6 is-offset-3">
      <article class="media">
        <div class="media-content">
          <%= form_with model: [article, comment], local: true do |form| %>
           
            <div class="field">
              <%= form.label :body, class: "label" %>
              <p class="control">
                  <%= form.text_area :body, class: "textarea", placeholder: "Add a comment..." %>
              </p>
            </div>
            <nav class="level">
              <div class="level-left">
              </div>
              <div class="level-right">
                <div class="level-item">
                  <%= form.submit submit, class: 'button is-info' %>
                </div>
                <div class="level-item">
                  <%= link_to "Cancel", article_path(article), class: 'button is-light' %>
                </div>
              </div>
            </nav>
          <% end %>
        </div>
      </article>
    </div>
  </div>
</div>

app/views/comments/edit.html.erb
<%= render 'form',
  article: @article,
  comment: @comment,
  heading: "Edit #{@article.title}'s comment",
  submit: "Update"%>

app/views/comments/new.html.erb
<%= render 'form',
  article: @article,
  comment: @comment,
  heading: "#{@article.title} - New Comment",
  submit: "Save"%>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>My Blog</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <section class="section">
      <%= render 'shared/nav_bar' %>
      <%= render 'shared/flash' %>
      
      <%= yield %>
    </section>
  </body>
</html>

app/views/shared/_flash.html.erb
<div class="container">
  <div class="columns is-multiline">
    <% flash.each do |name, msg| -%>

    <div class="column is-8 is-offset-2">
      <div class="notification has-text-centered is-<%= name %>">
        <%= msg %>
      </div>
    </div>

    <% end -%>
  </div>
</div>

app/views/shared/_nav_bar.html.erb
<div class="container">
  <nav class="navbar" role="navigation" aria-label="main navigation">
    <div class="navbar-brand">
      <%= link_to "My Blog", root_path, class: "navbar-item is-size-1"%>

      <a role="button" class="navbar-burger burger" aria-label="menu" aria-expanded="false" data-target="navbarBasicExample">
        <span aria-hidden="true"></span>
        <span aria-hidden="true"></span>
        <span aria-hidden="true"></span>
      </a>
    </div>

    <div id="navbarBasicExample" class="navbar-menu">
      <div class="navbar-end">
        <div class="navbar-item">
          <div class="buttons">
              <% if logged_in? %>
            <%= link_to "New Article", new_article_path, class: "button is-success is-rounded" %>
              <%= link_to "Log Out", logout_path, method: :delete, class: "button is-success is-rounded" %>
            <% else %>
              <%= link_to "Log In", login_path, class: "button is-info is-rounded" %>
              <%= link_to "Sign Up", users_signup_path, class: "button is-link is-rounded" %>
            <% end %>
          </div>
        </div>
      </div>
    </div>
  </nav>
</div>

app/views/users/new.html.erb
<div class="container">
  <div class="columns is-multiline">
    <div class="column is-6 is-offset-3">
      <div class="content is-size-3">
        <h1>New User</h1>
      </div>
    </div>

    <% if @user.errors.any? %>
      <div class="column is-6 is-offset-3">
        <article class="message is-danger">
          <div class="message-body">
            <p><%= pluralize(@user.errors.count, "error") %> prohibited this user from being saved:</p>
            <br>
            <p>
            <% @user.errors.full_messages.each do |msg| %>
              <li><%= msg %></li>
            <% end %>
            </p>
          </div>
        </article>
      </div>
    <% end %>

    <div class="column is-6 is-offset-3">
      <%= form_with model: @user, local: true do |form| %>
        <div class="field">
          <%= form.label :name, class: "label" %>
          <div class="control">
            <%= form.text_field :name, class: "input", placeholder: "Your name"%>
          </div>
        </div>

        <div class="field">
          <%= form.label :email, class: "label" %>

          <div class="control">
            <%= form.email_field :email, class: "input", placeholder: 'Your email' %>
          </div>
        </div>

        <div class="field">
          <%= form.label :password, class: "label" %>

          <div class="control">
            <%= form.password_field :password, class: "input", placeholder: 'Your password' %>
          </div>
        </div>

        <div class="field">
          <%= form.label :password_confirmation, class: "label" %>

          <div class="control">
            <%= form.password_field :password_confirmation, class: "input", placeholder: 'Confirm password' %>
          </div>
        </div>


        <div class="field is-grouped">
          <div class="control">
            <%= form.submit "Submit", class: "button is-link" %>
          </div>
          <div class="control">
            <%= link_to "Cancel", articles_path, class: 'button is-link is-light' %>
          </div>
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/users/show.html.erb
<div class="container">
  <div class="columns is-multiline">
    <div class="column is-6 is-offset-3">
      <div class="content is-size-3">
        <h3><%= @user.name %></h3>
        <p><%= @user.email %></p>
      </div>
    </div>
  </div>
</div>